// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	notification "github.com/machtwatch/catalyst-go-skeleton/infrastructure/notification"
	mock "github.com/stretchr/testify/mock"
)

// INotificationEmail is an autogenerated mock type for the INotificationEmail type
type INotificationEmail struct {
	mock.Mock
}

// Send provides a mock function with given fields: req, tmpl
func (_m *INotificationEmail) Send(req notification.EmailRequest, tmpl notification.EmailTemplate) error {
	ret := _m.Called(req, tmpl)

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.EmailRequest, notification.EmailTemplate) error); ok {
		r0 = rf(req, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewINotificationEmail interface {
	mock.TestingT
	Cleanup(func())
}

// NewINotificationEmail creates a new instance of INotificationEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewINotificationEmail(t mockConstructorTestingTNewINotificationEmail) *INotificationEmail {
	mock := &INotificationEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
