INSERT INTO public.ms_region_province (id,"name",code) VALUES
	 (1,'Aceh (NAD)','AC'),
	 (2,'Bali','BA'),
	 (3,'Banten','BT'),
	 (4,'Bengkulu','BE'),
	 (10,'Jawa Tengah','JT'),
	 (14,'Kalimantan Tengah','KT'),
	 (15,'Kalimantan Timur','KI'),
	 (7,'Gorontalo','GO'),
	 (23,'Nusa Tenggara Timur (NTT)','NT'),
	 (27,'Sulawesi Barat','SR'),
	 (25,'Papua Barat','PB'),
	 (30,'Sulawesi Tenggara','SG'),
	 (26,'Riau','RI'),
	 (6,'DKI Jakarta','JK'),
	 (5,'DI Yogyakarta','YO'),
	 (8,'Jambi','JA'),
	 (9,'Jawa Barat','JB'),
	 (11,'Jawa Timur','JI'),
	 (13,'Kalimantan Selatan','KS'),
	 (16,'Kalimantan Utara','KU'),
	 (17,'Kepulauan Bangka Belitung','BB'),
	 (18,'Kepulauan Riau','KR'),
	 (19,'Lampung','LA'),
	 (20,'Maluku','MA'),
	 (21,'Maluku Utara','MU'),
	 (22,'Nusa Tenggara Barat','NB'),
	 (24,'Papua','PA'),
	 (28,'Sulawesi Selatan','SN'),
	 (29,'Sulawesi Tengah','ST'),
	 (31,'Sulawesi Utara','SA'),
	 (32,'Sumatera Barat','SB'),
	 (33,'Sumatera Selatan','SS'),
	 (34,'Sumatera Utara','SU'),
	 (12,'Kalimantan Barat','KB');
